Corrected file

diff --git a/0x0C-web_server/4-not_found_page_404 b/0x0C-web_server/4-not_found_page_404
--- a/0x0C-web_server/4-not_found_page_404
+++ b/0x0C-web_server/4-not_found_page_404
@@ -1,10 +1,51 @@
 #!/usr/bin/env bash
-# Configures NGINX
-sudo apt-get update -y
-sudo apt-get install nginx -y
-sudo echo 'Hello World' > /var/www/html/index.html
-echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
-new_string="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
-nstr2="\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
-sed -i "s/server_name _;/$new_string$nstr2/" /etc/nginx/sites-enabled/default
-service nginx start
+# Installs and configures an Nginx web server
+# configure nginx to redirect /redirect_me to another page
+
+if dpkg -l | grep -q "nginx"; then
+    echo "Nginx is already installed."
+else
+    if ! sudo apt-get update; then
+        echo "Failed to update package lists. Exiting."
+        exit 1
+    fi
+
+    if ! sudo apt-get -y install nginx; then
+        echo "Failed to install Nginx. Exiting."
+        exit 1
+    fi
+fi
+
+# Allow Nginx HTTP traffic in the firewall using UFW
+if ! sudo ufw allow "Nginx HTTP"; then
+    echo "Failed to allow Nginx HTTP traffic in the firewall."
+fi
+
+# Create a Hello World index page
+echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
+
+# Check if Nginx configuration file exists
+if [ -e /etc/nginx/sites-available/default ]; then
+            # Backup existing configuration
+    if ! sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak; then
+         echo "Failed to backup the Nginx configuration. Continuing without backup."
+    else
+         echo "Nginx configuration backed up successfully."
+    fi
+
+fi
+
+# Add a redirect rule to Nginx configuration
+sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://github.com/henryno111 permanent; ' /etc/nginx/sites-available/default
+
+# Create a custom 404 page
+echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
+
+# Modify Nginx configuration to use custom 404 page
+replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
+sudo sed -i "s/listen 80 default_server;/$replace/" /etc/nginx/sites-available/default
+
+#Apply changes
+sudo service nginx restart
+
+echo "Nginx configured successfully."
